### ISSUE TITLE
Models to add to the UI

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap#1117]
### Description

List of flowsheets to "wrap" so they can be accessed through the UI

### Motivation

Need POC and flowsheet locations. Will need help choosing list of variables, etc.

### Additional Context

- Models that are currently UI-enabled are not as interesting/complex as others we have
- Therefore, we want to have more of the complex models (FIXME) to become UI-enabled to showcase the full potential of the GUI

## Wishlist
In order of priority

- [x] RO with energy recovery #1159 
- [x] IEDO full WWT (in addition to the Jupyter Notebook tutorial) (conventional BSM2 - as opposed to the extended version that's not fully working yet) #1125 
- [x] IEDO dye desal #1126 
- [ ] LSSRO (@zacharybinger, @adam-a-a) #1383 
- [ ] ED (@lbibl) #1439 
- [x] MVC (@MarcusHolly, @TimBartholomew) #1185 
- [x] GAC (@hunterbarber)  #1238
- [x] OARO (@luohezhiming) #1290

## UI questions

- Once we have these in, is there a way to group/identify/hide the simpler (current) models?
  - @MichaelPesce: working on categories
  - @adam-a-a what about "desalination & wastewater treatment"? or "detailed" and "simple"?

**Comment by hunterbarber** [comment]
@adam-a-a @TimBartholomew So I have a surrogate that reduces the parameter input for the CPHSDM GAC model. In all it adds two surrogate constraints to replace 7 parameters obtained from a lookup table. I think the plan is that once the corresponding manuscript is submitted/published, to add those surrogates as an config option to the model. With the GUI models, I'm assuming lower parameter input is preferred. Should the GAC hold off until the surrogates have been implemented in main or should the GAC model for the GUI include these parameters that are readily available, but need looked up in literature as a function of other values in the model?

**Comment by ksbeattie** [comment]
@dangunter  do you want to split apart the issues that will be in the March release into a separate issue and close this one for the Dec release?

**Comment by adam-a-a** [comment]
@hunterbarber I think the UI should have the 7 parameters (the As and Bs I am assuming) with defaults in there. Later we could think about adding the option to switch to a custom surrogate, with yours surrogates being the default forms.

**Comment by hunterbarber** [comment]
> @hunterbarber I think the UI should have the 7 parameters (the As and Bs I am assuming) with defaults in there. Later we could think about adding the option to switch to a custom surrogate, with yours surrogates being the default forms.

Are they not already provided? [watertap/examples/flowsheets/gac/gac_ui.py#L601](https://github.com/hunterbarber/watertap/blob/main/watertap/examples/flowsheets/gac/gac_ui.py#L601) And I agree I think that is the plan once those surrogates are added to the repo

**Comment by adam-a-a** [comment]
> > @hunterbarber I think the UI should have the 7 parameters (the As and Bs I am assuming) with defaults in there. Later we could think about adding the option to switch to a custom surrogate, with yours surrogates being the default forms.
> 
> Are they not already provided? [watertap/examples/flowsheets/gac/gac_ui.py#L601](https://github.com/hunterbarber/watertap/blob/main/watertap/examples/flowsheets/gac/gac_ui.py#L601) And I agree I think that is the plan once those surrogates are added to the repo

Sorry, this was my response to your previous [comment](https://github.com/watertap-org/watertap/issues/1117#issuecomment-1833860288) that you posted back in November. I realized afterwards that your question was already resolved and the GAC UI was merged.
