### ISSUE TITLE
BSM2 tasks for September 2023 release

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1165]
The following tasks were accomplished in time for the September 2023 release and originated from #934:

- [x] Export BSM2 (with ASM1/ADM1) to GUI #1125 
- [x] Modify dewaterer and thickener to be compatible with other ASM models #1078
- [x] Full BSM2 flowsheet using ADM1 & ASM1 #1038 
- [x] Implement translator block for ASM2D-> modified ADM1 w/ P extension #1074 
- [x] Update ADM1 & modified ADM1 documentation based on the refinements in #1038 
- [x] Refinement of initial ADM1/AD implementation, including scaling/initialization as needed #909 
- [x] Refinement of scaling in ASM1 #1038 
- [x] #1002
