### ISSUE TITLE
Merge in Stakeholder Code Demos

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1173]
This is a reminder to put up PRs for and merge code demos presented at the IDAES stakeholder meeting. I thought the demos were all great, and we should make them accessible to all.

Please add any that I may be omitting. Note: some may require more revision than others (e.g., if new code was shown that hasn't been reviewed/merged yet), but we should aim to get everything merged in after some iteration:

- [x] adding custom constraints to models- @avdudchenko #1163 
- [x] parameter sweep demo - @k1nshuk #1181
- [x] parameter estimation demo - @OOAmusat @savannahsakhai #1182
- [x] OLI demo - @veccp #1141 
- [x] connecting flowsheets to UI - @MichaelPesce #1152
- [x] multi-period modeling - @zacharybinger (will reference on watertap-reflo issue too since it might belong in that repo since we use pysam)
