### ISSUE TITLE
Costing in BSM2

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1217]
Add initial costing to BSM2 flowsheet:

- [x] Implement all costing into BSM2 flowsheet #1213 
- [x] Anaerobic digestor  #1196 #1045 
- [x] Primary Clarifier #1198 #1215 
- [x] Secondary Clarifier #1198 #1215 
- [x] Thickener #1216 
- [x] Dewatering Unit #1212 
- [x] Aeration basin for activated sludge process (w/ or w/o compressor costs?) #1196 
- [x] Anerobic/Anoxic basin for activated sludge process #1186 

Refinements may be needed to incorporate O&M costs across units to ensure balanced comparisons. That is, the same set of cost assumptions/considerations should be made for each unit.
