### ISSUE TITLE
Add documentation for flowsheet examples

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1219]
None of our flowsheet examples have documentation. This is a considerable gap, and we should add docs for these. Moreover, as we add flowsheets to the GUI (see issue #1117), the need for documentation will increase. I will add an asterisk for those we should prioritize as high priority and a tilde (~) for those we may want to deprioritize. In terms of prioritization, all are still up for discussion though.

EDIT: Tagging people who I think should at the very least should be key points of contact for each:

# For March 2024:
- [x] BSM2 flowsheet* @adam-a-a @agarciadiego @MarcusHolly #1263 and #1354

# For June 2024:
- [x] RO w/ERD* @kurbansitterley #1446 
- [x] MD* @ElmiraShamlou #1444 
- [x] GAC* @hunterbarber #1396 
- [x] NaCl Crystallizer * @OOAmusat #1403 
- [x] ED * @lbibl #1385 #1386 
- [x] IX #1418 
- [x] LSRRO* @adam-a-a @ElmiraShamlou #1450
- [x] MVC* @MarcusHolly @ElmiraShamlou #1430 
- [x] OARO* @luohezhiming #1351 
- [x] Activate Sludge Model 1 (ASM1) flowsheets @agarciadiego #1376 
- [x] ASM2d flowsheets @agarciadiego @adam-a-a @luohezhiming #1376 
- [x] ADM1 flowsheet @agarciadiego #1376 
- [x] ~~electroN-P flowsheet @luohezhiming~~
- [x] ~~Municipal Treatment case study (originally from WT3) @kurbansitterley @TimBartholomew~~
- [x] Seawater RO case study (originally from WT3) @kurbansitterley @TimBartholomew #1425
- [x] ~~14 zero-order WRRF cases associated with IEDO 2336 @adam-a-a @MarcusHolly @luohezhiming @agarciadiego~~

**---Unit Model Documentation---**
- [x] CSTR (mostly a copy of the IDAES CSTR) #1379 
- [x] CSTR with injection (Aeration Tank) #1379 
- [x] Primary Clarifier #1379 
- [x] Secondary Clarifier #1379

**Comment by adam-a-a** [comment]
@dangunter highlighted the fact that this effort should also work in coordination with the UI (e.g., being able to point to or pull up model descriptions via the UI)
