### ISSUE TITLE
Clean up WaterTAP

### ISSUE THREAD

**Issue by TimBartholomew** [watertap-org/watertap#1248]
WaterTAP is past due for some general cleaning of unused/obsolete code and reorganizing some of the repo. For example, recently we decided to remove the chemistry tests in #1229. We should use this issue to identify other clean up opportunities.

Prioritized clean up:
- [x] Remove watertap/unit_models/nanofiltration_0D, this was one of the first models added to WaterTAP but there are many known issues. The biggest issue is that it is only applicable for binary mixtures (one salt and water) but the primary reason to use nanofiltration is for selective removal of divalents and monovalents. Additionally, we have two other NF models that are more applicable. (#1334)
- [x] Remove watertap/flowsheets/full_treatment_train, this was an important flowsheet for a ProteusLib (previous name for WaterTAP) milestone in Sept 2021 but it is finicky (oftentimes tests need to be changed) and it is convoluted. Additionally, many of the assumptions for the water chemistry are troubling, we have much better non-public work for this same type of analysis. (#1335)
- [x] Move the electrolyte database to a new repository, we've had various discussions around this, currently I believe the consensus is that its maintenance is not worth it when it is used so little @lbianchi-lbl
- [x] Remove watertap/unit_models/selective_oil_permeation and watertap/property_models/selective_oil_permeation_prop_pack, these are simple models that were made for a collaboration that ended without results (#1336)
- [x] Rework watertap/examples/custom_model_demo, this should be converted into a jupyter notebook and a tutorial #1390 @MarcusHolly 
- [x] Move property models that are specific to unit models (e.g. cryst_prop_pack, coagulation_prop_pack) into a new folder for these limited property packages (maybe watertap/property_models/unit_specific) @savannahsakhai #1429 
- [x] Remove seawater_ion_generic and seawater_ion_prop_pack, these are likely obsolete to MCAS (#1347)
- [x] Remove IEDO simple flowsheets from GUI @MarcusHolly #1417
- [x] Reorganize and purge watertap/examples/flowsheets/case_studies. This structure was made to isolate/bury the non-predictive models. Instead, I believe we should rename this folder something like "zero_order". All flowsheets that are not zero order like BSM1, BSM2, etc. should just be moved up to flowsheets (we want these to be visible anyways). In my opinion, all FOA 2336 zero order flowsheets that do not have an active collaboration should be removed (we can always dig them back up if we begin working with the teams in the future). @MarcusHolly #1438 

Potential clean up:

- [ ] Move watertap/examples into its own repository (potentially a lot of work and conflicting with WaterTAP GUI)

**Comment by kurbansitterley** [comment]
A few ideas: 

- Re-evaluate / remove / consolidate zero order models.
- Develop standard naming convention for unit_models (i.e. some have "0D" appended, some do not)
- Create separate directory for 0D vs 1D models?
- Personal crusade: change ``aggregate_flow_electricity`` to ``aggregate_flow_power`` since we are actually aggregating power demand (correct me if I'm wrong)

**Comment by adam-a-a** [comment]
General comment is whether we should "rework" or "replace" some of these instead of "remove" them. The full treatment train is one example that comes to mind.

**Comment by bknueven** [comment]
> General comment is whether we should "rework" or "replace" some of these instead of "remove" them. The full treatment train is one example that comes to mind.

I would vote in favor of "remove", unless we have a priority to develop similar capability. I could imagine "rework" would be considerable effort for the full treatment train.

If a capability we remove suddenly becomes relevant again we can always retrieve it from the history and rework it (if necessary) at that point.

**Comment by lbianchi-lbl** [comment]
Related to #1230; I've created a `spring-cleaning` label to keep these issues grouped together.

**Comment by adam-a-a** [comment]
Closed #659 , #694, and #1065 --- all stranded draft PRs.

**Comment by adam-a-a** [comment]
> * Personal crusade: change `aggregate_flow_electricity` to `aggregate_flow_power` since we are actually aggregating power demand (correct me if I'm wrong)

@kurbansitterley this has bothered for quite some time too--the incorrect labeling of "energy" for terms that are actually tied to power.

**Comment by adam-a-a** [comment]
Personally, rather than make this some large effort that all gets pushed through in one quarter, I would vote to chip away at this over time since we have many other priorities that involve new development and analyses.

**Comment by adam-a-a** [comment]
> * [ ]  Remove watertap/unit_models/nanofiltration_0D, this was one of the first models added to WaterTAP but there are many known issues. The biggest issue is that it is only applicable for binary mixtures (one salt and water) but the primary reason to use nanofiltration is for selective removal of divalents and monovalents. Additionally, we have two other NF models that are more applicable.

I want to add that this model brought in the Kedem-Katchalskiy model, which we now have integrated into the RO model through config options. Notably, that new RO formulation will also only be applicable for binary mixtures, which is more of a limitation of the SKK model I think (though I did go hunting through literature for multicomponent applications and turned up a result or two).

Overall, I agree-mostly because we represent the SKK model somewhere else now.
