### ISSUE TITLE
Feature suggestions for OLI Cloud API

### ISSUE THREAD

**Issue by veccp** [watertap-org/watertap#1279]
### Description

This issue tracks tasks to help with OLI Cloud API development. 

**Fixes for March 2024 release:**
- [x] Enable all flash calculations (isenthalpic, etc.) (#1296)
- [x] Enable any input parameters to be surveyed (pH, etc.) (#1296)
- [x] Enable reconciliation options (pH, alkalinity, total inorganic carbon, etc.) (#1296)
- [x] Enable other thermodynamic frameworks as required for corrosion analysis (#1296)
- [x] Exception handling for empty results (#1296)
- [x] Apply absolute/relative status to all survey variables (not just solutes) (#1296)
- [x] Address workflow bottlenecks for true/apparent species (#1296)
- [x] Revision of extracting/handling data from JSON output (#1296)

_Tasks last updated: March 14, 2024_
