### ISSUE TITLE
Applying Unit Test Harness

### ISSUE THREAD

**Issue by MarcusHolly** [watertap-org/watertap#1302]
### Description

To be completed in the December release:
- [ ] Ultraviolet Advanced Oxidation Process @luohezhiming 
- [ ] Dewatering Unit @adam-a-a 
- [ ] Electrodialysis 0D & 1D @lbibl 
- [ ] ElectroN-P @luohezhiming 
- [ ] Nanofiltration (0D, DSPMDE, & ZO) @adam-a-a 
- [ ] Pressure Exchanger @luohezhiming 
- [ ] Stoichiometric Reactor @avdudchenko 

Completed in the June release:
- [x] Boron Removal @savannahsakhai #1415
- [x] Coag & Floc @MarcusHolly #1363
- [x] CSTR @agarciadiego #1371 
- [x] CSTR Injection @agarciadiego #1371 
- [x] Ion Exchange @kurbansitterley 
- [x] 0D Membrane Distillation @ElmiraShamlou 
- [x] Osmotically Assisted Reverse Osmosis (0D & 1D) @luohezhiming #1367 
- [x] Pressure Changer @MarcusHolly #1363
- [x] Thickener @agarciadiego  #1371 

Completed in the March Release:
- [x] Reverse Osmosis (0D & 1D) @MarcusHolly #1301 
- [x] Clairifer @MarcusHolly #1301 
- [x] Crystallizer @MarcusHolly #1301 
- [x] Granular Activated Carbon @hunterbarber #1311 
- [x] Electrolyzer @hunterbarber #1321
- [x] 1D Membrane Distillation @ElmiraShamlou #1323  

### Motivation

This will make unit model testing more standardized across the repository.

### Possible Implementation

See [Anaerobic Digester Test.](https://github.com/watertap-org/watertap/blob/main/watertap/unit_models/tests/test_anaerobic_digester.py)

**Comment by hunterbarber** [comment]
Can I make some changes to `UnitTestHarness` to add a `self.costing_model_block` to also assert values on `m.fs.costing` via `self.costing_solutions[m.fs.costing.variable] = value`? @TimBartholomew @MarcusHolly Thoughts?

**Comment by MarcusHolly** [comment]
`m.fs.costing` seems like it would involve multiple unit models (i.e. a flowsheet), so that seems more like a test that should be included in flowsheet tests as opposed to unit model tests. That being said, do you have an example/application in mind where you think it would be beneficial to have assert the values of `m.fs.costing` because maybe I'm just missing something.

**Comment by hunterbarber** [comment]
So maybe this is a call back to the prior decision that the unit model costing blocks don't have a dedicated test folder, and therefore have been tested in the unit model tests. In `test_gac.py` I  was testing the costing package for coverage, but depending on the model (for a single unit model flowsheet) the `m.fs.costing` or `m.fs.unit.costing` may be referenced to assert values. So maybe this just means translating the `m.fs.costing.variable` checks to the `m.fs.unit.costing.variable` components that can still be accessed through `unit_solutions[]` (I think?)

**Comment by MarcusHolly** [comment]
Hmmm, I see. So the options would be to (1) make changes to the UnitTestHarness as you mentioned above or (2) choose to not test `m.fs.costing` in these tests at all. I'm curious what @TimBartholomew or others think.

As far as translating from `m.fs.costing.variable` to `m.fs.unit.costing.variable`, I'm not sure how trivial this is. I tried doing so in the existing GAC test and I get an `AttributeError`

**Comment by hunterbarber** [comment]
I have up the GAC test converted to the harness up until the costing variable checks. So I can push for more context but yea, I was also just curious for opinions.

**Comment by hunterbarber** [comment]
The solution may also be to create a `CostingTestHarness` in addition to the options we already brought up

**Comment by MarcusHolly** [comment]
> The solution may also be to create a `CostingTestHarness` in addition to the options we already brought up

I think this sounds good, especially for scenarios where we want to test keeping the operating conditions the same but only change how the costing is handled.

**Comment by TimBartholomew** [comment]
@MarcusHolly @hunterbarber I think since IDAES and WaterTAP are organized around property, unit, and cost models as separate, that we should make a separate `CostingTestHarness` and that those tests live under the costing folder.

I think we've been a little loose with mixing unit and cost models together and that in general we should separate them more, specifically the tests and documentation (right now we don't really have costs documented, some unit models have them at the end of their unit model documentation but not all).

The challenge that I see is that the costing test needs a unit model built, specified, and solved (which is what the UnitTestHarness does). I think it would be bad to duplicate the whole unit model build and specification in a separate test file under the costing folder that then uses the CostingTestHarness (one of the points of test harness was to reduce copying and pasting), maybe what we do is that the costing test file imports the build/specifying the variables from the unit test file.

Anyways, what should we do now with our cost tests without a `CostingTestHarness` being made? I think there are two options:

1. Create a test file for the unit model costing, under the watertap/costing/unit_models/tests. Where you import the build function that creates the unit model and specifies the variables that you made for the UnitTestHarness. Then add costing, scale the model, initialize, and solve, and check costing outputs.
2. Maybe after doing 1, it would be easy and clear to adapt the UnitTestHarness to a new CostingTestHarness to handle the scaling, intialize, solve, and check costing outputs steps

**Comment by andrewlee94** [comment]
For testing costing, you should mock up a unit model that has only the variable that costing requires. E.g.,

```
m.dummy_unit = Block()
m.dummy_unit.area = Var()
m.dummy_unit.area.fix(...)

# Add costing to unit
```

This will let you unit test the costing in isolation. You can then add some integration tests where you double check that it works with a full unit, but you cn run these more sparingly.

**Comment by TimBartholomew** [comment]
Ohhh interesting. Yeah that could be best. That way all the unit model costing doesn't have to fully solve the detailed model, which is already tested.

**Comment by hunterbarber** [comment]
> For testing costing, you should mock up a unit model that has only the variable that costing requires. E.g.,
> 
> ```
> m.dummy_unit = Block()
> m.dummy_unit.area = Var()
> m.dummy_unit.area.fix(...)
> 
> # Add costing to unit
> ```
> 
> This will let you unit test the costing in isolation. You can then add some integration tests where you double check that it works with a full unit, but you cn run these more sparingly.

The WaterTAP costing package does inherit the costing method based on the unit model class, so there will have to be some slightly strategic dummy blocks made here. I'm going to play around with the idea in #1311.

**Comment by MarcusHolly** [comment]
> > For testing costing, you should mock up a unit model that has only the variable that costing requires. E.g.,
> > ```
> > m.dummy_unit = Block()
> > m.dummy_unit.area = Var()
> > m.dummy_unit.area.fix(...)
> > 
> > # Add costing to unit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will let you unit test the costing in isolation. You can then add some integration tests where you double check that it works with a full unit, but you cn run these more sparingly.
> 
> The WaterTAP costing package does inherit the costing method based on the unit model class, so there will have to be some slightly strategic dummy blocks made here. I'm going to play around with the idea in #1311.

Alright, I will play around with this in my PR as well whenever I have some free time.
