### ISSUE TITLE
Running TO-DO for conventional BSM2 Flowsheet

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1318]
There are some outstanding to-do items for the BSM2 flowsheet, most of which were mentioned in #1244:

- [ ] add temp dependence for KLa and consider moving to ASM prop models and off of cstr_injection unit
- [ ] add temp dependence for S_O_eq and move to prop model
- [ ] revisit origin of 1.8 factor and more general aeration energy equation; 1.8 may be the aeration efficiency which is oxygen mass transfer divided by power input
- [x] Resolve final iterations of BSM2 flowsheet having regularization #1469 
- [ ] Probe model solutions across range of initial conditions as well as altering setup of optimization model
- [ ] use Henry's law constant for co2 already created in ADM1 rxn model; remove the `KH_co2` from anaerobic digester
- [ ] move any other variables/parameters that shouldn't be on AD unit to props or reactions (`K_La`, `KH_ch4`, ...)
- [ ] resolve the danger of redundant constraint related to pressure equality constraints created in **Mixer** unit, specifically for isobaric conditions. the mixer initializer will turn these constraints back on
- [ ] **consider** adding costs for mixers, separators, any auxiliary units that aren't explicitly costed (without double counting)
- [ ] change ref to m.fs.Treated instead of CL1 effluent in `add_effluent_violations` function
- [ ] revisit rector volume equality constraints used to facilitate optimization of AS reactor volumes

**Comment by adam-a-a** [comment]
We should revisit " Resolve final iterations of BSM2 flowsheet having regularization" and make sure this wasn't confused with ending in restoration. Either way, let's check the conventional BSM2 flowsheet solver output.

**Comment by adam-a-a** [comment]
> change ref to m.fs.Treated instead of CL1 effluent in add_effluent_violations function

@MarcusHolly attempted to make this change, but for some reason, it caused test failures for the GUI, and so the changes were undone. We should revisit this issue at some point.
