### ISSUE TITLE
Feature Requests for OLI API

### ISSUE THREAD

**Issue by veccp** [watertap-org/watertap#1328]
### Description
This issue tracks tasks to help with OLI Cloud API development, in approximate order of priority.
_Tasks last updated: June 28, 2024 by @adam-a-a _

- [ ] Add a concentration_factor_survey function to make it easier to quickly run OLI calculations that simulate water recovery and elevated concentrations (and associated scaling tendencies)
- [ ] Resolve units issues preventing a future concentration_factor_survey from working #1458 
- [ ] Enable bubblepoint function to work without error #1388 
- [ ] Enable dewpoint, vapor-amount, vapor-fraction, and isochoric functions to work without error
- [ ] Asynchronous calls to the API (#1303)
- [ ] Sequential surveys, e.g., chemical additions followed by pH adjustment
- [ ] Improve test coverage (>80%);  Add more rigorous testing to cover all existing functionality (including exception handling)
- [ ] Improve CredentialManager class (#1300)
- [ ] Interface with WaterTAP and simplify usage
- [ ] Docstring clarity and consistency with rest of WaterTAP (imports, structure, naming conventions, etc.)
- [ ] Add rules for liquid2 (non-aqueous liquid) phase
- [ ] Add features for OLI Flowsheet

**Comment by adam-a-a** [comment]
Adding an item here that I think should be a priority before making major changes or additions to the API:

- [ ] Add more rigorous testing to cover all existing functionality (including exception handling)
