### ISSUE TITLE
Adding cost documentation

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1360]
**Running to do list:**

- [x] Add cost landing page #1361 

**Costing technical references for** 

- [x] Mixer (can be minimal but should clean up the template at least) @MarcusHolly #1456 
- [x] RO @adam-a-a #1395 
- [x] GAC @hunterbarber #1375
- [x] aeration tank @MarcusHolly #1373
- [x] anaerobic digester @agarciadiego #1433 
- [x] clarifier @MarcusHolly #1373
- [x] compressor @ElmiraShamlou #1442  
- [x] crystallizer @OOAmusat #1391 
- [x] cstr injection @MarcusHolly #1373
- [x] cstr @MarcusHolly #1373
- [x] dewatering @MarcusHolly #1373
- [x] electrodialysis @lbibl @hunterbarber #1454 
- [x] electrolyzer @hunterbarber #1392
- [x] electroN-P @luohezhiming #1377 
- [x] ERD @adam-a-a #1395 
- [x] evaporator @ElmiraShamlou #1442 
- [x] heat exchanger @ElmiraShamlou #1442 
- [x] heater_chiller @ElmiraShamlou #1442 
- [x] IX @kurbansitterley #1402 
- [x] MD @ElmiraShamlou #1442 
- [x] NF @adam-a-a #1395
- [x] OARO @luohezhiming #1377 
- [x] Pressure exchanger  @adam-a-a #1395
- [x] Pump @adam-a-a #1395
- [x] stoichiometric reactor @avdudchenko #1449
- [x] thickener @MarcusHolly #1373
- [x] UV AOP @luohezhiming #1377

**Comment by adam-a-a** [comment]
Woohoo!
