### ISSUE TITLE
Checklist for model enhancements

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#1463]
# Checklist for model enhancements

- [ ] revise tds calculation in mcas to allow for flexibility in how the calculation is made instead of accounting only for ions
- [ ] revise osmotic pressure calc in mcas to account for apparent species instead ions only
- [ ] enable the provision of custom methods in RO (and other models?), e.g., custom friction factor 
- [ ] add dynamic capability to RO model
