### ISSUE TITLE
EDB Roadmap

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#171]
This is the start of a living document for desired EDB behaviors/functionality. The list below should roughly represent order of priority. 

- [x] Update 'get_reactions' behavior to grab the set of reactions that contains only the set of species given (#164)
- [x] Fix 'bug' in how ions are represented by having them all defined as 'aqueousPhase' and with a corresponding 'charge' (#163)
- [x] Document how to use the EDB
- [x] Set reaction orders using api function (#266 )
- [x] Create a 'get_all_possible_reactions' function that will return all reactions that might occur from a given set of components

Please add to, change, or modify this list as needed.
