### ISSUE TITLE
WaterTAP Costing Package Enhancements

### ISSUE THREAD

**Issue by bknueven** [watertap-org/watertap#402]
We should do a bit of clean-up from #393 
- [x] Remove stub files in watertap/examples/flowsheets/full_treatment_train/model_componets/ https://github.com/watertap-org/watertap/pull/393#discussion_r823917728 #495 
- [x] Support more than one LCOW / specific energy consumption https://github.com/watertap-org/watertap/pull/393#discussion_r823893782 (#497)
- [x] Clean-up NaOCl / CaOH2 flow costing https://github.com/watertap-org/watertap/pull/393#discussion_r823932410 (#496)
- [x] Cost electricity flow with units as in Zero-Order package (#504) https://github.com/watertap-org/watertap/blob/53ac11da291f2c48a7fbc5d14b493f5d1fbcb960/watertap/core/zero_order_costing.py#L296-L298
- [ ] Add better documentation for WaterTAPCosting package
- [x] Add explicit tests for WaterTAPCosting package (Question: should tests live with the costing package or the unit model? https://github.com/watertap-org/watertap/pull/515#discussion_r863022357)
- [x] Incorporate any upcoming changes to LSRRO flowsheet if needed (Issue #461, #518)
- [ ] Organize parameters for specific unit models:
    - Put parameters for a unit model on their own block
    - Lazily create said block the first time that unit model is costed.

**Comment by bknueven** [comment]
I'm going to close this -- the open issues are captured in #676
