### ISSUE TITLE
Nanofiltration DSPM-DE Enhancement

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#464]
The initial version of the nanofiltration DSPM-DE was pushed in PR#465, but the model needs to undergo validation and refinement.
To Do List:
**DSPM-DE Model:**
_Model Enhancement_
- [ ] Add pressure loss relationship for spiral wound membrane module
- [ ] Add modified mass transfer coefficient due to suction effect
- [ ] Revise documentation as needed: add degrees of freedom and identify variables typically fixed, etc.
- [ ] Expand to 1D and possibly 2D to account for gradient across membrane pore and membrane length
- [ ] Reformulate potentially problematic constraints

_Stability and Testing_
- [x] Refine initialization as needed to enhance stability
- [x] Refine scaling as needed to enhance stability- thanks to @bknueven 
- [x] Augment and refine tests
- [ ] Continue refinement of initialization for more robust model
- [x] Continue refinement of scaling for more robust model - thanks to @bknueven @avdudchenko for contributions 
- [ ] Rigorously validate the model and refine implementation as needed

_Parameter Estimation_
- [ ] Enable parameter estimation of pore radius, effective thickness, pore dielectric constant, and charge density

**MCAS Property Model**
- [ ] add calc option for Stokes radius from Stokes Einstein
- [ ] get relationship for viscosity as a func of temp and concentration for undefined solute set
- [ ] get relationship for density as a func of temp and concentration for undefined solute set (using seawater correlation currently)
- [ ] consider adding the Pitzer activity coefficient model (nice-to-have)
- [ ] consider adding OLI API functionality (nice-to-have)
- [ ] Refine documentation as needed
- [x] Remove H2O from molecular weight data input requirement. MCAS should contain MW of H2O by default.
- [x] consider changing Solute to Anion or Cation (#501)
- [x] **ADD documentation** @lbibl - the issue is being tracked here. #858 
- [x] Rename the `pressure_osm` property to `pressure_osm_phase` in order to be more consistent with IDAES generic property package (#501)
- [x] Refine initialization, scaling, and bounds on variables/constraints (#508)

**Comment by aladshaw3** [comment]
In #508 I have suggested (and merged in) skipping of the nanofiltration tests from initialization onwards. Results of my analysis on the initialization failures suggest that the changes in the property model are not the issue with the failing tests, but the unit model itself (which may need to be reformulated in some manner). 

Here is the log from the initialization showing that convergence for the property package is smooth and normal, but the initialization of the unit model fails to ever find a solution.

[nanofiltration_DSPMDE_initialization_log.txt](https://github.com/watertap-org/watertap/files/8583099/nanofiltration_DSPMDE_initialization_log.txt)

**Comment by aladshaw3** [comment]
I think that the main issue with the model is a combination of scaling and initialization. In the current initialization method, it does not appear as though you are performing any initial guessing for the variables this model introduces and are instead just calling the solver from what ever the current state is. I think you can improve things by performing some simple calculations based on the state variables to more properly provide an initial value to the variables this unit introduces BEFORE calling any solver.

**Comment by lbibl** [comment]
Merging #858 will check one box here.

**Comment by adam-a-a** [comment]
@avdudchenko reported that stateblocks don't successfully initialize when trying an example with 2 ions at very low concentrations. This should be probed further to ensure model stability.
