### ISSUE TITLE
Electrodialysis Model Development List - June

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#489]
To Do List for Electrodialysis Unit Model:
--------------------------------------------
- [x] Complete first iteration of 0D electrodialysis model [**April**] (#523)
- [x] Make necessary changes in ion properties for electrodialysis [**April**] 
     - (issue #464)
     - (PR #501)
     - (PR #508)
- [x] Create documentation for 0D electrodialysis [**June**] (#537)
- [x] Complete first iteration of 1D electrodialysis model [**June**] (#571 )
- [x] Create documentation for 1D electrodialysis [**June**] (#579)
- [x] **Costing** for analysis in flowsheets (#582)

**Comment by lbibl** [comment]
I updated with some proposed 0d refinements .
