### ISSUE TITLE
Boron Removal Model Development

### ISSUE THREAD

**Issue by aladshaw3** [watertap-org/watertap#492]
To Do List:
-----------
- [x] Equilibrium reactor for boron speciation [**June/July**] (#531)
- [x] Zero order boron removal unit [**June**] (#531)
- [x] Boron Removal Documentation (#536)
- [ ] Demonstration for boron removal in flowsheet [**June**]
- [ ] Boron specific RO unit ?? [**If needed**]

**Comment by aladshaw3** [comment]
Should be done as a unit model that contains the IDAES unit model for equilibrium reactor including H+, OH-, H2O, Boron speciation, and added NaOH (or other base)

**Comment by aladshaw3** [comment]
May be good to validate against an OLI simulation
