### ISSUE TITLE
Variable efficiency models for pumps

### ISSUE THREAD

**Issue by arao53** [watertap-org/watertap#641]
Implement efficiency correlations or characteristic curves for pumps that operate outside the best efficiency point. Constant efficiency is modeled in `pump_electricity_ZO`.

- [x] Low pressure (< 10bar) pumps with efficiency-flow correlations for ZO pump model. PR #640 
- [x] 0D pump unit that inherits from the IDAES pump unit model (similar to WaterTAP Isothermal Pump). PR #654 
- [x] Implement flow-head-efficiency correlations in the 0D pump unit model. #719

**Comment by arao53** [comment]
Zero order pump is being replaced by 0D pump model, which builds on top of the WaterTAP Isothermal Pump model. Next steps include implementing pump efficiency correlations with relevance to desalination applications.

**Comment by arao53** [comment]
Items 1 and 2 have been closed and item 3 is now being tracked by issue #719.
