### ISSUE TITLE
WaterTAP costing improvements

### ISSUE THREAD

**Issue by TimBartholomew** [watertap-org/watertap#676]
There are a few potential improvements that I've been thinking about for WaterTAP costing:

- [x] Moving the creation of *global* unit costing parameters (typically fixed variables) from the build_global_params in the costing package to the unit costing methods (Done in #835 for WaterTAPCosting Package, ~~TODO for ZeroOrderCosting Package~~) (Working on #911 I realized the ZO Costing package has *always* done this.)

The benefits would include:
- Avoiding the creation of the parameters if the unit is not costed on the flowsheet, currently all of the costing parameters get added regardless of whether the unit exists. The issue is that when someone displays the costing parameter block there are many unused parameters and is confusing for the user - this will only grow as we add more units.
- The unit costing method could create a block with the unit name to the costing package parameter block, this would help with the name space and organization of the parameters

- [ ] Moving the unit costing methods to their unit models (Started in #835 for WaterTAPCosting Package, DONE in #911 for ZeroOrderCosting Package, Completed in #1122)

The benefits would include:
- Clearer separation of the system costing and the unit costing, this also helps with documentation. The unit costing could have their own technical reference page.
- Making it easier for users to see what is required for creating a custom unit costing because each unit costing file is essentially an example.
- It would make it more clear to users if we have multiple costing methods for a unit, they could see multiple costing files and import them as needed as opposed to configuration arguments that I think is more convoluted

- [ ]  Documentation (e.g., #723) (Completed in #1122, moved to #1135)
- [ ]  #710 (Completed in #1122)
- [x] Allow user-settable `base_currency`, and hard-code all parameters to use a fixed year. (Done in #835)
- [x] Rename `Var` / `Param`s for flow cost (e.g., `electricity_base_cost`) to `{flow_type}_cost` (e.g., `electricity_cost`) using IDAES/idaes-pse#983; (#865)
- [x] Consider combining the two costing packages into a single package (moved to #1134)

**Comment by andrewlee94** [comment]
As a comment regarding point 1: consider whether these parameters are something that should be varied globally (e.g. during sensitivity studies). If they are something that should be equal across all units, you really want them in a single, centralized location, otherwise the parameter can be varied locally for each unit resulting in inconsistencies.

**Comment by bknueven** [comment]
> As a comment regarding point 1: consider whether these parameters are something that should be varied globally (e.g. during sensitivity studies). If they are something that should be equal across all units, you really want them in a single, centralized location, otherwise the parameter can be varied locally for each unit resulting in inconsistencies.

Thanks @andrewlee94. I've updated Tim's comment to reflect that the parameters should still be global, but instead of being built with the costing package construction they should be on-demand.

We could still include them in the costing package itself (similar to on-demand properties), but it might makes sense to put their definition in the same place as the unit model costing methods. The exact implementation is still to be determined.

**Comment by ksbeattie** [comment]
@bknueven looks like some of the above checkboxes can be checked?

**Comment by lbianchi-lbl** [comment]
Not sure if or how much of this is planned for June. @adam-a-a suggests we should prioritize documentation for developers.

**Comment by adam-a-a** [comment]
I wonder if we should add something to this list regarding the combining of two or more costing packages on a given flowsheet. @avdudchenko mentioned the same in Slack.

**Comment by lbianchi-lbl** [comment]
As per @bknueven: the design work on this is complete, and the implementation could be done quickly, but it would affect any other PR dealing with costing, so it ends up being a "rip the band-aid" situation.

**Comment by lbianchi-lbl** [comment]
- Development will pick back up starting next week (@bknueven)
- Considerations/features that are relevant for WaterTAP-SETO and other dependent projects (brought up by @adam-a-a)
