### ISSUE TITLE
Master issue UI 9/30 release

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap#721]
## For demo
- [x] Make sure flowsheet is updated after solve #727 
- [x] Incorporate unit conversion for UI values #725 
- [x] Address rounding issues on UI when rounding is 0 or negative @MichaelPesce 
- [x] Make sure for every flowsheet that has a UI interface, there is an associated diagram @dangunter
    - [x] METAB #717 

## For release
- [x] #712 , which will pass tests more easily once the next item in this list is complete (since currently it breaks the `.find()` tests)
- [x] Change `FlowsheetInterface.find()` to use "entry points" in the (currently non-existent) `setup.py` instead of searching/importing modules. This will also require some rewriting of the logic in the class constructor and the watertap-ui `backend/app/internal/settings.py` module. @lbianchi-lbl and @MichaelPesce
    - https://github.com/watertap-org/watertap-ui/pull/59 
- [x] Ideally have a simple script, doing roughly what the current FlowsheetInterface.find() does, that can update the entry points from the watertap source at packaging time, since Tim B. said there will be about a dozen flowsheets exported by 9/30. But arguably this is trivial to do by hand even at this scale: find / grep / cut and paste.
- [x] Add "Delete config" button
    - https://github.com/watertap-org/watertap-ui/pull/68
- [x] #755 

Please update this with comments, additional items, etc. @MichaelPesce @lbianchi-lbl @TimBartholomew
