### ISSUE TITLE
GUI-Flowsheet Implementation Checklist

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap#777]
### **We need to connect the following AMO flowsheets to the GUI.**

- [x] 1581 #757 
- [x] 1611 #776 
- [x] 1617 #762 
- [x] 1664 #698 
- [x] 1595 #763 
- [x] 1679 #767 
- [x] 1614 #765 
- [x] 1690 #772 
- [x] 1598 #752 
- [x] 1575 #769 #775 #759 
- [x] 1503 #771 
- [x] 1669 #792

**Comment by adam-a-a** [comment]
### Additional running to-do list for refinement:
### For release
- [x] Add all entry_points in setup.py
- [x] Add images for each flowsheet. Thus far, METAB has one, and dye desal has a temporary one. https://github.com/watertap-org/watertap/issues/782
- [x] Calculation of direct capital costs in flowsheets and/or GUI code may be erroneous if `cost_factor` is not set to `TIC` for corresponding unit yaml files. Fix this once the GUI PRs are in place. #793

**Comment by lbianchi-lbl** [comment]
@adam-a-a thanks for putting the list together. I'll create a draft PR adding the entry points for the flowsheets that have been merged in already but don't have one yet.

**Comment by MarcusHolly** [comment]
An additional item we can could add to the running to-do list is to verify whether the descriptions for variables in the output tab are visible when you hover over them (or maybe it just doesn't work for me).

**Comment by lbianchi-lbl** [comment]
> An additional item we can could add to the running to-do list is to verify whether the descriptions for variables in the output tab are visible when you hover over them (or maybe it just doesn't work for me).

@MarcusHolly That's a good point. Without knowing the details, I'd say it sounds more like a purely UI-specific issue (unless e.g. within the same flowsheet, the description-on-hover works for some of the variables, but not all of them), so maybe opening an issue in watertap-org/watertap-ui would be more fitting.
