### ISSUE TITLE
flowsheet-diagrams

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap#782]
Diagrams for UI flowsheets.

## Images for diagrams

- [x] Image for #757  - Chenyu
- [x] Image for #776  - Adam
- [x] Image for #762  - Chenyu
- [x] Image for #698 - Tim
- [x] Image for #763 - Travis
- [x] Image for #767  - Travis
- [x] Image for #765  - Chenyu
- [x] Image for #772 - Travis
- [x] Image for #752 - Chenyu
- [x] Image for #769 -  Marcus
- [x] Image for #775 - Travis
- [x] Image for #759 - Marcus
- [x] Image for #771 - Adam
