### ISSUE TITLE
ADM1 refinement

### ISSUE THREAD

**Issue by agarciadiego** [watertap-org/watertap#909]
### Description

- [x] Include Carbon and Inorganic Nitrogen dioxide acid-base equilibrium constant #918 
- [x] Include Henry's law coefficient for gas species #918 
- [x] The summation symbol is not displaying in the Anaerobic digestor unit model documentation (1st equation in table) - #878 
- [x] refine initialization if/as needed #1038 
- [x] refine scaling if/as needed #1038 
- [x] probe stability of expression-if usage for the pH dependent expressions to better understand potential points of instability, if any, introduced by inclusion of expression-ifs #1038 changed to smooth max
- [x] remove unnecessary imports; e.g., noticed import of Degeneracy Hunter in the flowsheet example for the anaerobic digestor, which was used for debugging and should be removed. #915 
- [x] Add class documentation at the end of AD unit (remembered we don't do this for prop models typically but wonder if we want to) #915 
- [x]  TODO note regarding use of correct conversion number for `concentration_of_co2_rule`

### Motivation

While the ADM1 model has been merged, we want to reflect on points of further refinement to the associated property and reaction models, as well as the anaerobic digestor unit model and all associated documentation. We will be using this work for creating a benchmark simulation model no. 2 (BSM2) flowsheet and anticipate this to be useful to wastewater treatment experts. As such, we expect to fine-tune ADM1-related code as we proceed.

**Comment by adam-a-a** [comment]
I made a number of comments in PR#857. We should revisit those and add to this task list as appropriate.

**Comment by lbianchi-lbl** [comment]
Last open task (as of 8/31) might be negligible and/or not an issue anymore (pending confirmation from @agarciadiego)
